### ISSUE TITLE
Running out of PSP

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/cohomolo#5]
I've added PR #1 adding a test file based on the first of the two examples from `testdata/test.g`. The 2nd example from there fails with `Out of space.Increase PSP.` error - I don't know where to set it as many source filed have `# define PSP` lines with different values of PSP.

```
gap> testdatadir := DirectoriesPackageLibrary( "cohomolo", "testdata" );;
gap> Read( Filename ( testdatadir, "a6" ) );
gap> chr:= CHR( G, 3, F, m3 );;
gap> M:= SchurMultiplier( chr );
#I  Indices in the subgroup chain are:  10 4 
#I   Cohomolo package: Calling external program.
Out of space.Increase PSP.
#I   External program complete.
Error, 'Cohomolo' failed for some reason.
 called from
Cohomolo( chr, true, false, false, TmpName(  ) 
 ); at /Users/alexk/gap4r8p1/pkg/cohomolo/gap/coho4.g:880 called from
<function "SchurMultiplier">( <arguments> )
 called from read-eval loop at line 80 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

**Comment by alex-konovalov** [comment]
The message is printed by `standalone/progs.d/conpdc1.c` but there is no `# define PSP` line there...

**Comment by alex-konovalov** [comment]
With increases info level, the error looks like
```
gap> M:= SchurMultiplier( chr );
#I   Cohomolo package: Calling external program.
#I/Users/alexk/gap4r8p1/pkg/cohomolo/bin/x86_64-apple-darwin14.5.0-gcc-5-defau\
lt64/cohomology.gap -mn 3 /tmp/gaptempfile.gztXeJ
Out of space.Increase PSP.
#I   External program complete.
Error, 'Cohomolo' failed for some reason.
 called from
Cohomolo( chr, true, false, false, TmpName(  ) 
 ); at /Users/alexk/gap4r8p1/pkg/cohomolo/gap/coho4.g:880 called from
<function "SchurMultiplier">( <arguments> )
 called from read-eval loop at line 81 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

**Comment by alex-konovalov** [comment]
I've rebuilt cohomolo with gcc 5.2.0 installed using Homebrew and the problem disappeared. I will now update my PR #1 with another example. This show how testing is important !

**Comment by alex-konovalov** [comment]
Thank you to Derek who explained this to me today:

The cohomolo package consists of a large number of separate C programs, most of which define (their own value of) PSP.  To find out exactly which C program was running when the crash occurred, edit `cohomolo/bin/execcmd.gap` file and insert the line
```
verbose=true
```
at the beginning of that file. Then it should print out each program call before running it.

**Comment by alex-konovalov** [comment]
Resolved for now - the remedy is to used gcc instead of clang on OS X. Similar problems known for KBMAG. It may have sense to get to the original problem and make it working with clang - I've filed #6 to remind of that.

**Comment by fingolfin** [comment]
I am not sure why this was closed and a new issue was opened -- this issue is *not* resolved, as it still occurs; we merely discovered that it depends on the compiler whether the failure appears or not... Since #6 contains far less details (e.g. no information on what the failure is, how to track down which of the many executables triggers it ec.), I have reopened this issue and closed #6.

**Comment by alex-konovalov** [comment]
ok - maybe #6 should be deleted in this case...

**Comment by fingolfin** [comment]
I don't think you can delete issues, just close them
